version: "3.9"
services:
  dev:
    build:
      context: ./
      target: dev
    container_name: devc
    ports:
      - 8080:8080
  db:
    build:
      context: ./
      target: db
    container_name: dbc
  adminer:
    image: adminer
    ports:
      - 3306:8080
