version: "3.9"
services:
  prod:
    build: ./
    container_name: prodc
    volumes: 
      - "./prod:/opt/app"
    ports:
      - 8080:8080
  db:
    image: mysql:8.3.0
    container_name: dbc
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 49152:8080
