version: "3.9"
services:
  prod:
    build:
      context: ./
      target: prod
    container_name: prodc
    ports:
      - 8080:8080
  db:
    build:
      context: ./
      target: db
    container_name: dbc
  adminer:
    image: adminer
    ports:
      - 3306:8080
